import BillionItem from "@/components/billion-item";
import { Metadata } from "next";
import Image from "next/image";
import { useRouter } from "next/navigation";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export interface Billions {
  id: string;
  name: string;
  squareImage: string;
  netWorth: number;
  industries: string[];
}

const getBillions = async () => {
  const res = await fetch("https://billions-api.nomadcoders.workers.dev/").then(
    (res) => res.json()
  );

  return res as Billions[];
};

export default async function Home() {
  const billions = await getBillions();

  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <ul className="grid grid-cols-4 gap-x-3 gap-y-6 ">
        {billions.map((billion) => (
          <BillionItem key={billion.id} billion={billion} />
        ))}
      </ul>
    </main>
  );
}
